name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: default


model-paths:
  - models
macro-paths:
  - macros
seed-paths:
  - seeds
test-paths:
  - tests
analysis-paths:
  - analyses
target-path: target
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages

models:
      +materialized: table