models:        
  - name: stg_orders

    columns:
      - name: order_id
        tests:
          - not_null
          - unique:
              config:
                severity: warn
                error_if: ">10"
                warn_if: ">1"
                
          
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          
  - name: stg_items
    columns:
      - name: item_id
        tests:
          - unique
          - not_null
  - name: stg_products
    columns:
      - name: sku
        tests:
          - unique
          - not_null

  - name: stg_stores
    columns:
      - name: store_id
        tests:
          - unique
          - not_null
  - name: stg_supplies
    columns:
      - name: supplies_id
        tests:
          - unique
          - not_null
          
          

          
          
              
              
    